### ISSUE TITLE
请问oauth/token如何访问？

### ISSUE THREAD

**Issue by liuchun2000** [goahead77/sso-server#1]
$2a$10$PKye/5vFmfq8dpKJJwnnbu5zd4A/.p3jaA4fsV3HzQCkIvdV0.j9K. 这串password是什么啊？

**Comment by goahead77** [comment]
这个就是用BCypt加密算法加密后的密码

**Comment by WenSteven** [comment]
> $2a$10$PKye/5vFmfq8dpKJJwnnbu5zd4A/.p3jaA4fsV3HzQCkIvdV0.j9K. 这串password是什么啊？

这个就是用BCypt加密算法加密后的密码

**Comment by liuchun2000** [comment]
> > $2a$10$PKye/5vFmfq8dpKJJwnnbu5zd4A/.p3jaA4fsV3HzQCkIvdV0.j9K. 这串password是什么啊？
> 
> 这个就是用BCypt加密算法加密后的密码

加密之前是什么？能给个oauth/token的访问参数吗

**Comment by WenSteven** [comment]
> > > $2a$10$PKye/5vFmfq8dpKJJwnnbu5zd4A/.p3jaA4fsV3HzQCkIvdV0.j9K. 这串password是什么啊？
> > 
> > 
> > 这个就是用BCypt加密算法加密后的密码
> 
> 加密之前是什么？能给个oauth/token的访问参数吗

加密之前的内容你可以通过单元测试 `@Autowired PasswordEncoder passwordEncoder` encoder下就可以拿到了，至于oauth/token ，你可以按照readme把demo跑起来，看network，就可以看到了。时间久矣，记不住了
